<?php

namespace App\Controller\Admin;

use App\Entity\Order;
use App\Form\OrderDetailType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use EasyCorp\Bundle\EasyAdminBundle\Collection\FieldCollection;
use EasyCorp\Bundle\EasyAdminBundle\Collection\FilterCollection;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Assets;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Context\AdminContext;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Dto\EntityDto;
use EasyCorp\Bundle\EasyAdminBundle\Dto\SearchDto;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\MoneyField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGenerator;
use Symfony\Component\HttpFoundation\RedirectResponse;

class OrderCrudController extends AbstractCrudController
{

    public function __construct(
        public AdminUrlGenerator $adminUrlGenerator,
    )
    {
    }

    public static function getEntityFqcn(): string
    {
        return Order::class;
    }

    public function configureActions(Actions $actions): Actions
    {

        $updatePreparation = Action::new('updatePreparation', 'Préparation en cours')->linkToCrudAction('updatePreparation');
        return $actions
            ->add('detail', $updatePreparation)
            ->add('index', 'detail');
    }

    public function updatePreparation(AdminContext $context): RedirectResponse
    {

        $order = $context->getEntity()->getInstance();
        $order->setState(2);

        $url = $this->adminUrlGenerator->setController(OrderCrudController::class)
            ->setAction('index')
            ->generateUrl();

        return $this->redirect($url);

        // add your logic here...
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
//            ->setFormThemes(['admin/_details.html.twig', '@EasyAdmin/crud/_detail.html/twig'])
            ->
        setDefaultSort(['id' => 'DESC']);
    }

    public function createIndexQueryBuilder(SearchDto $searchDto, EntityDto $entityDto, FieldCollection $fields, FilterCollection $filters): QueryBuilder
    {
        $qb = parent::createIndexQueryBuilder($searchDto, $entityDto, $fields, $filters); // TODO: Change the autogenerated stub

        $qb
            ->leftJoin('entity.orderDetails', 'details')
            ->leftJoin('details.produit', 'product')
            ->leftJoin('product.shop', 'shop');

        $qb->andWhere('shop.id = :shop_id')
            ->setParameter('shop_id', '5');

//        $qb->andWhere('details.product IN (:product_name)')
//            ->setParameter('product_name', 'lorem');


        return $qb;
    }

    public function configureFields(string $pageName): iterable
    {

        return [

            TextField::new('user.fullName', 'Client')->hideOnForm(),
            DateTimeField::new('createdAt', 'Passée le'),
            TextField::new('carrierName', 'Livreur'),
            MoneyField::new('carrierPrice', 'Coùt de Livraison')->setCurrency('XOF'),
            ChoiceField::new('state')->setChoices([
                'Non payée' => 0,
                'Payée' => 1,
                'Préparation en cours' => 2,
                'Livraison en cours' => 3,
            ]),
            MoneyField::new('total', 'Total')->setCurrency('XOF'),
//            ArrayField::new('orderDetails')->onlyOnDetail(),
            CollectionField::new('orderDetails', 'Produits de la commande')
//                ->setEntryType(OrderDetailType::class)
//                ->useEntryCrudForm(OrderDetailsCrudController::class)
                ->setTemplatePath('admin/_details.html.twig')
                ->onlyOnDetail(),
        ];
    }




}
