<?php

namespace App\Controller\Admin;

use App\Entity\OrderDetails;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class OrderDetailsCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return OrderDetails::class;
    }

    public function configureActions(Actions $actions): Actions
    {
        $changeState = Action::new('changeState', 'Changer état')
            ->setIcon('fa fa-sync')
            ->linkToCrudAction('changeStateAction');
        return $actions
            ->add(Crud::PAGE_INDEX, $changeState)
            ->add(Crud::PAGE_DETAIL, $changeState);
            // TODO: Change the autogenerated stub
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('product '),
        ];
    }

}
